// This file is auto-generated by @hey-api/openapi-ts

export { type Options, TinyMceService } from './sdk.gen';
export type { ClientOptions, GetConfigData, GetConfigError, GetConfigErrors, GetConfigResponse, GetConfigResponses, OpenAiApiConfig, ProblemDetails, RichTextEditorCommand, RichTextEditorCommandModeModel, RichTextEditorSettings, TinyMceConfig, TinyMceConfigResponseModel } from './types.gen';
