// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44308/' | (string & {});
};

export type OpenAiApiConfig = {
    model: string;
    developerMessage: string;
    temperature: number | string;
    maxCompletionTokens: number | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type RichTextEditorCommand = {
    alias: string;
    name: string;
    mode: RichTextEditorCommandModeModel;
};

export type RichTextEditorCommandModeModel = number;

export type RichTextEditorSettings = {
    commands: Array<RichTextEditorCommand>;
    plugins: Array<string>;
    customConfig: {
        [key: string]: unknown;
    };
    validElements: string;
    invalidElements: string;
    cloudApiKey?: null | string;
};

export type TinyMceConfig = {
    apikey: string;
    tinyMceVersion: string;
    tinyMceUrl: string;
    openAiApikey: string;
    pluginsToExclude: Array<string>;
    openAiApiConfig: OpenAiApiConfig;
    sanitizeTinyMce: boolean;
    customConfig: {
        [key: string]: unknown;
    };
};

export type TinyMceConfigResponseModel = {
    richTextEditor?: null | RichTextEditorSettings;
    config?: null | TinyMceConfig;
};

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/tiny-mce/config';
};

export type GetConfigErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * OK
     */
    200: TinyMceConfigResponseModel;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];
